# Generated by Django 2.2.10 on 2020-03-20 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tabelog', '0002_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='image_url',
        ),
    ]
